import {
  Aim,
  Bell,
  Box,
  Calendar,
  Collection,
  DataAnalysis,
  Document,
  DocumentCopy,
  Edit,
  Files,
  Folder,
  Grid,
  House,
  Key,
  Link,
  List,
  Location,
  Lock,
  MagicStick,
  Management,
  Memo,
  Menu,
  Message,
  Monitor,
  Notebook,
  OfficeBuilding,
  Operation,
  Platform,
  Postcard,
  PriceTag,
  Search,
  SetUp,
  Setting,
  Share,
  Stamp,
  Switch,
  Tickets,
  Tools,
  TrendCharts,
  User,
  UserFilled,
  View,
  Warning
} from '@element-plus/icons-vue'

export const iconMap: Record<string, unknown> = {
  Aim,
  Bell,
  Box,
  Calendar,
  Collection,
  DataAnalysis,
  Document,
  DocumentCopy,
  Edit,
  Files,
  Folder,
  Grid,
  House,
  Key,
  Link,
  List,
  Location,
  Lock,
  MagicStick,
  Management,
  Memo,
  Menu,
  Message,
  Monitor,
  Notebook,
  OfficeBuilding,
  Operation,
  Platform,
  Postcard,
  PriceTag,
  Search,
  SetUp,
  Setting,
  Share,
  Stamp,
  Switch,
  Tickets,
  Tools,
  TrendCharts,
  User,
  UserFilled,
  View,
  Warning
}

export const iconOptions = [
  { label: '工作台', value: 'DataAnalysis' },
  { label: '系统设置', value: 'Setting' },
  { label: '菜单权限', value: 'Menu' },
  { label: '角色/人员', value: 'UserFilled' },
  { label: '用户', value: 'User' },
  { label: '组织机构', value: 'OfficeBuilding' },
  { label: '权限钥匙', value: 'Key' },
  { label: '锁定权限', value: 'Lock' },
  { label: '任务工单', value: 'Tickets' },
  { label: '文档', value: 'Document' },
  { label: '文档副本', value: 'DocumentCopy' },
  { label: '流程', value: 'Operation' },
  { label: '日历计划', value: 'Calendar' },
  { label: '设备监控', value: 'Monitor' },
  { label: '集合目录', value: 'Collection' },
  { label: '管理', value: 'Management' },
  { label: '工具', value: 'Tools' },
  { label: '配置', value: 'SetUp' },
  { label: '列表', value: 'List' },
  { label: '网格', value: 'Grid' },
  { label: '文件夹', value: 'Folder' },
  { label: '文件', value: 'Files' },
  { label: '备忘', value: 'Memo' },
  { label: '笔记', value: 'Notebook' },
  { label: '编辑', value: 'Edit' },
  { label: '首页', value: 'House' },
  { label: '链接', value: 'Link' },
  { label: '位置', value: 'Location' },
  { label: '搜索', value: 'Search' },
  { label: '查看', value: 'View' },
  { label: '消息', value: 'Message' },
  { label: '平台', value: 'Platform' },
  { label: '卡片', value: 'Postcard' },
  { label: '标签', value: 'PriceTag' },
  { label: '分享', value: 'Share' },
  { label: '印章', value: 'Stamp' },
  { label: '开关', value: 'Switch' },
  { label: '趋势图', value: 'TrendCharts' },
  { label: '目标', value: 'Aim' },
  { label: '魔法棒', value: 'MagicStick' },
  { label: '告警', value: 'Warning' },
  { label: '盒子', value: 'Box' },
  { label: '通知', value: 'Bell' }
]

export function getIconComponent(iconName: string) {
  return iconMap[iconName] || Document
}
